import { Property } from './types'

export default {
  CheckValue: () => import('./read/check.vue'),
  ColorValue: () => import('./read/color.vue'),
  DateValue: () => import('./read/date.vue'),
  ImageValue: () => import('./read/image.vue'),
  VideoValue: () => import('./read/video.vue'),
  PlainValue: () => import('./read/plain.vue'),
  ArrayValue: () => import('./read/array.vue'),
  ObjectValue: () => import('./read/object.vue'),
  EnumValue: () => import('./read/enum.vue'),
  FileValue: () => import('./read/file.vue'),
  HtmlValue: () => import('./read/html.vue'),
  EditorValue: () => import('./read/editor.vue'),
  CheckField: () => import('./edit/check.vue'),
  ColorField: () => import('./edit/color.vue'),
  DateField: () => import('./edit/date.vue'),
  ImageField: () => import('./edit/image.vue'),
  VideoField: () => import('./edit/video.vue'),
  NumberField: () => import('./edit/number.vue'),
  PlainField: () => import('./edit/plain.vue'),
  TextareaField: () => import('./edit/textarea.vue'),
  ArrayField: () => import('./edit/array.vue'),
  ObjectField: () => import('./edit/object.vue'),
  EnumField: () => import('./edit/enum.vue'),
  FileField: () => import('./edit/file.vue'),
  Codemirror: () => import('../codemirror.vue'),
  EditorField: () => import('./edit/editor.vue'),
}

export const viewMap: Record<Property.Type, string> = {
  string: 'plain-value',
  number: 'plain-value',
  textarea: 'plain-value',
  json: 'json-value',
  bool: 'check-value',
  date: 'date-value',
  color: 'color-value',
  image: 'image-value',
  video: 'video-value',
  object: 'object-value',
  enum: 'enum-value',
  file: 'file-value',
  html: 'html-value',
  editor: 'editor-value',
}

export const editMap: Record<Property.Type, string> = {
  string: 'plain-field',
  number: 'number-field',
  textarea: 'textarea-field',
  json: 'json-field',
  bool: 'check-field',
  date: 'date-field',
  color: 'color-field',
  image: 'image-field',
  video: 'video-field',
  object: 'object-field',
  enum: 'enum-field',
  file: 'file-field',
  html: 'plain-field',
  editor: 'editor-field',
}
